### ISSUE TITLE
这是恶意骚扰

### ISSUE THREAD

**Issue by Ahtaler** [Sakitami/trojan-subscription-builder#1]
哇啦哇啦好厉害

**Comment by Sakitami** [comment]
Tks,if you wanna encourage me,please give me a star,or buy me a cola : )

**Comment by Ahtaler** [comment]
讲人话，星星我不是给了吗，可乐没有，王老吉好不好

Sakitami <notifications@github.com>于2020年3月6日 周五下午5:17写道：
